# Generated by Django 6.0 on 2026-01-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_alter_servico_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='codigo',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
