# Generated by Django 6.0 on 2026-01-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0006_alter_cliente_nome_alter_contrato_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='valor_negociado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco_base',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
