# Generated by Django 6.0 on 2026-01-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_alter_cliente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
