# Generated by Django 6.0 on 2026-01-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0005_alter_contrato_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_negociado',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco_base',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
